[package]
name = "sprite_sheets"
version = "0.1.0"
authors = ["Stallmanifold <stallmanifold@gmail.com>"]

[dependencies]
glfw = "0.23.0"
gl = "0.10.0"
chrono = "0.4.2"
scan_fmt = "0.1.3"
stb_image = "0.2.2"
png = "0.12.0"
assimp = "0.3.1"
